### ISSUE TITLE
クリア、ゲームオーバー問わずタイトルに戻らず次のゲームが始まってしまうことがある

### ISSUE THREAD

**Issue by Athron** [makochang/DonPeroKi#106]

**Comment by makochang** [comment]
目に見えないところで、「タイトルに戻る」→「ボタン押されたのでゲームシーンへ」が実行されているものと信じたい。
確認お願いします
@nature5884

**Comment by nature5884** [comment]
AnyKeyでとってるので連打等していると一瞬でゲームシーンへ飛びます
