### ISSUE TITLE
マイルストーンとイシュー

### ISSUE THREAD

**Issue by makochang** [makochang/DonPeroKi#15]
@nature5884 
@H-Kuramoto 
@ShinichiMatsushita 
@NishimatsuYuki 
@nkckawachi 

プロトタイプ完成に向けて、マイルストーンを設定し、プロトタイプに必要そうなことをイシューとして登録しました。
イシューをクローズするたびにマイルストーンのメーターが増えます。
過不足あれば追加もしくは提案してください。
この仕組みうざいですか？

**Comment by makochang** [comment]
コメントできるぜ

**Comment by nature5884** [comment]
クローズしたら@makochangさんにメールが飛ぶぞ！
たくさん終わらせて復讐しよう！

**Comment by nature5884** [comment]
testcomment

**Comment by makochang** [comment]
プロトタイプ完成おめでとうございます。
次はα版に向けて頑張りましょう。
