### ISSUE TITLE
戦闘システムをラッシュに変更

### ISSUE THREAD

**Issue by H-Kuramoto** [makochang/DonPeroKi#20]
BFとかのラッシュ戦ね

MAPに拠点が幾つかあり、その拠点を全て制圧されると敗北。
自軍は敵を拠点を守りつつ敵を殲滅するのが目的となる。
今回のゲームの場合はエース機の破壊が勝利条件

**Comment by makochang** [comment]
BFって何ですか？

**Comment by makochang** [comment]
@nature5884 
バトルフィールドのラッシュモードの防衛側のイメージ
フィールドには敵機体、自軍機体、自軍拠点が存在しており、自軍機体の全滅もしくは自軍拠点の全破壊で敗北となる。

**Comment by makochang** [comment]
#52 に統合します
