### ISSUE TITLE
仮ゲームタイトルの命名

### ISSUE THREAD

**Issue by makochang** [makochang/DonPeroKi#40]
@nature5884 
@H-Kuramoto 
@ShinichiMatsushita 
@NishimatsuYuki 
@nkckawachi 
@Athron 
@ryoten82 

# タイトル案
## 敵の強大さを強調したタイトル
* アーチエネミー（Archenemy）：大敵。サタンを意味する場合も。
* アンタゴニスト（Antagonist）：敵役（かたきやく）。
* ネメシス（Nemesis）

## 置かれている状況などを説明するタイトル
* ディスアドバンテージ（Disadvantage）：不利
* アンフェイヴラブル（Unfavorable）：不利

**Comment by makochang** [comment]
量産機無双

**Comment by NishimatsuYuki** [comment]
量産機でGO!

**Comment by H-Kuramoto** [comment]
Suicidal Rebellion（スーサイダルリベリオン）
自殺的反抗って言う意味です（かっこいい）

**Comment by NishimatsuYuki** [comment]
Suicidal RebellionでGO!!
がいい

**Comment by makochang** [comment]
スーサイドはさぁ、ねぇ

**Comment by H-Kuramoto** [comment]
社会的にNG???

**Comment by makochang** [comment]
エロゲー作るくらい面倒臭い
政治的に

**Comment by H-Kuramoto** [comment]
映画のタイトルとかで使われてるしってなったんですけど最近でもまだまだNGでしょうか？？
学校的には確かにきつそうなワードですが、、、一応まだ考えるって話なんで別案も出ると思います。

**Comment by makochang** [comment]
@H-Kuramoto 
ケチがつきそうな気がする

**Comment by makochang** [comment]
Rebellionに決定しました。クローズします。
