### ISSUE TITLE
α版で使用する背景データの作成

### ISSUE THREAD

**Issue by makochang** [makochang/DonPeroKi#43]
* UE4プロジェクトをAssetsリポジトリにプッシュしてください。本リポジトリへの取り込みは@nature5884が担当します。
* タスクが全て完了したらクローズしてください。

# タスク
α版 #42 で使用するダミーマップをUE4のレベルとして作成してください。マップで使用するアセットにはコリジョンメッシュを追加してください。

## 手順
1. 拠点、汎用ビルA、汎用道路をDCCツールで作成し、FBX化する
2. UE4に読み込み配置する
3. レベルを保存する
4. 仮マップとして@nature5884に渡す
5. 残りのアセットを作成し、FBX化する
6. 既存のマップを再構成する
7. レベル保存する
8. 本マップとして@nature5884に渡す

### 仮マップ
- [x] 拠点
- [x] 汎用ビルA（30m級）
- [x] 汎用道路（直線）
- [x] 汎用道路（交差点）

### 本マップ
- [x] 汎用ビルB（30m級）
- [x] 汎用ビルC（30m級）
- [x] 汎用ビルD（30m級）
- [x] 汎用ビルE（60m級）
- [x] 汎用ビルF（60m級）

## ヘルプ
* [コリジョンメッシュ](https://docs.unrealengine.com/latest/JPN/Engine/Content/FBX/StaticMeshes/index.html#%E3%82%B3%E3%83%AA%E3%82%B8%E3%83%A7%E3%83%B3)

**Comment by NishimatsuYuki** [comment]
コリジョンできました！やはり、おなまえいれる欄間違えていたようです。

**Comment by makochang** [comment]
アセットの渡し方が変更になったため、内容を一部修正しました。

**Comment by makochang** [comment]
終わったタスクは順次チェック入れてください

**Comment by makochang** [comment]
終わったみたいなのでクローズします
