### ISSUE TITLE
敵が全ての拠点を破壊できない

### ISSUE THREAD

**Issue by makochang** [makochang/DonPeroKi#57]
迷子です。

![notworkenemy](https://cloud.githubusercontent.com/assets/3254388/12196253/a3d942e4-b640-11e5-925e-4f9e161b8693.jpg)

**Comment by makochang** [comment]
完全勝利
![notworkenemy](https://cloud.githubusercontent.com/assets/3254388/12196762/bf5043e8-b644-11e5-9d28-d90e661f8a4b.jpg)

**Comment by nature5884** [comment]
多分直ったはず！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
